### ISSUE TITLE
Add alerts if things get out of control

### ISSUE THREAD

**Issue by mpchadwick** [AOEpeople/Aoe_DbRetry#3]
Would you be interested in adding in something to send alerts if things start failing a lot? Perhaps there is an admin interface (or even configuration node) for a threshold of number of time the retry failed altogether in an hour (haven't fully though through the architecture). We have a situation where this is a requirement so I'm trying to determine this is a change that you would incorporate upstream or it should be handled through a rewrite on our end. If you'd be interested I could prep a PR.

**Comment by LeeSaferite** [comment]
Well, if it's fairly light weight I'd be interested for sure. Issue a PR and we can talk it over. I look forward to your contribution.
